### ISSUE TITLE
human_default and zombie_default models won't set, only motherzombie

### ISSUE THREAD

**Issue by BoTo-sg** [Oylneechan/ZombieSharp#3]
human_default and zombie_default models won't set, only motherzombie
/zclass displays wrong info as well after typing !1 and !2

11:36:07 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '"human_default"' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ZombieSharp.ZombieSharp.PlayerClassSelectMenu(CCSPlayerController client, Int32 team) in E:\Github\ZSharp\ZombieSharp\ZombieSharp\PlayerClasses.cs:line 153
   at ZombieSharp.ZombieSharp.<PlayerClassMainMenu>b__60_1(CCSPlayerController client, ChatMenuOption option) in E:\Github\ZSharp\ZombieSharp\ZombieSharp\PlayerClasses.cs:line 141
   at CounterStrikeSharp.API.Modules.Menu.BaseMenuInstance.OnKeyPress(CCSPlayerController player, Int32 key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/BaseMenu.cs:line 119
   at CounterStrikeSharp.API.Modules.Menu.MenuManager.OnKeyPress(CCSPlayerController player, Int32 key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/MenuManager.cs:line 72
   at CounterStrikeSharp.API.Core.Application.<>c.<Start>b__16_0(CCSPlayerController player, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Application.cs:line 101
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 154
   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass7_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 105
   
   11:30:13 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '"zombie_default"' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ZombieSharp.ZombieSharp.PlayerClassSelectMenu(CCSPlayerController client, Int32 team) in E:\Github\ZSharp\ZombieSharp\ZombieSharp\PlayerClasses.cs:line 150
   at ZombieSharp.ZombieSharp.<PlayerClassMainMenu>b__60_0(CCSPlayerController client, ChatMenuOption option) in E:\Github\ZSharp\ZombieSharp\ZombieSharp\PlayerClasses.cs:line 140
   at CounterStrikeSharp.API.Modules.Menu.BaseMenuInstance.OnKeyPress(CCSPlayerController player, Int32 key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/BaseMenu.cs:line 119
   at CounterStrikeSharp.API.Modules.Menu.MenuManager.OnKeyPress(CCSPlayerController player, Int32 key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Menu/MenuManager.cs:line 72
   at CounterStrikeSharp.API.Core.Application.<>c.<Start>b__16_0(CCSPlayerController player, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Application.cs:line 101
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 154
   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass7_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 105

**Comment by Oylneechan** [comment]
what is your playerclasses.json look like?

**Comment by BoTo-sg** [comment]
I am using custom models with the default playerclasses.json file and the latest counterstrikesharp version.
It worked before until the latest ZombieSharp version

{
    "PlayerClasses":{
        "human_default": {
            "Name": "Human Default",
            "Description": "Default Class for human",
            "Enable": true,
            "Team": 1,
            "Model": "characters/models/s2ze/master_chief/low/master_chief_low.vmdl",
            "MotherZombie": false,
            "Health": 150,
            "Regen_Interval": 0.0,
            "Regen_Amount": 0,
            "Speed": 250.0,
            "Knockback": 0.0,
            "Jump_Height": 1.0,
            "Jump_Distance": 1.0
        },
        "zombie_default": {
            "Name": "Zombie Default",
            "Description": "Default Class for zombie",
            "Enable": true,
            "Team": 0,
            "Model": "characters/models/s2ze/zombie_frozen/zombie_frozen.vmdl",
            "MotherZombie": false,
            "Health": 5000,
            "Regen_Interval": 10.0,
            "Regen_Amount": 100,
            "Speed": 280,
            "Knockback": 3.0,
            "Jump_Height": 1.0,
            "Jump_Distance": 1.0
        },
        "motherzombie": {
            "Name": "Mother Zombie",
            "Description": "Mother Zombie Class",
            "Enable": true,
            "Team": 0,
            "Model": "characters/models/s2ze/chris_walker/chris_walker.vmdl",
            "MotherZombie": false,
            "Health": 15000,
            "Regen_Interval": 10.0,
            "Regen_Amount": 100,
            "Speed": 280,
            "Knockback": 3.0,
            "Jump_Height": 1.0,
            "Jump_Distance": 1.0
        }
    }
}

**Comment by Oylneechan** [comment]
as the json file the one / is not enough
```json
{
    "PlayerClasses":{
        "human_default": {
            "Name": "Human Default",
            "Description": "Default Class for human",
            "Enable": true,
            "Team": 1,
            "Model": "characters\\models\\s2ze\\master_chief\\master_chief_nohitbox.vmdl",
            "MotherZombie": false,
            "Health": 150,
            "Regen_Interval": 0.0,
            "Regen_Amount": 0,
            "Speed": 250.0,
            "Knockback": 0.0,
            "Jump_Height": 1.08,
            "Jump_Distance": 1.0,
            "Fall_Damage": false
        }
    }
}
```

**Comment by BoTo-sg** [comment]
that didn't help either, if I use 1 \ instead of two \ it will produces a lot of errors but If I use it the other way / one time, it will work fine but still does what this report is about.

it happens without going into /zclass

**Comment by Oylneechan** [comment]
I did test and it work fine for me, I need more specific version of cssharp you use now and the os, I run on v179 with ubuntu 20.04.

**Comment by BoTo-sg** [comment]
I am running counter strike sharp 187

I also noticed another bug, did you delete zombiesharp.db and start fresh?

Go to /game/csgo/cfg/zombiesharp/zombiesharp.cfg
zs_classes_mother_default "motherzombie" is listed as the wrong cvar, its zs_classes_motherzombie_default in the code and
when I change it to zs_classes_motherzombie_default in the configs, it stops setting the mother zombie model.

**Comment by BoTo-sg** [comment]
In regards to /myclass, this is what came up with even when motherzombie

Human Class: "human_default"
Zombie Class: "zombie_default"
Active Class: "human_default"

**Comment by Oylneechan** [comment]
> that didn't help either, if I use 1 \ instead of two \ it will produce a lot of errors but If I use it the other way / one time same as \\ two times, motherzombie still is the only one that works.

I insist that it will need to be ``//`` and not ``/``, even it won't work now it has to be ``//`` because that is how json syntax work. If you insist to not change it, it will not work at all.

> I am running counter strike sharp 187 but it also does it on 179
You didn't tell me your server OS

> I also noticed another bug, did you delete zombiesharp.db and start fresh?
No

> Go to /game/csgo/cfg/zombiesharp/zombiesharp.cfg zs_classes_mother_default "motherzombie" is listed as the wrong cvar, its zs_classes_motherzombie_default in the code and when I change it to zs_classes_motherzombie_default in the configs, it stops setting the mother zombie model.
zs_classes_motherzombie_default is the correct convar, I have only have two theories about this issues is
1. Those // stuff I mention earlier.
2. PrecahceResource plugin still remain running. and not disable since a newer version of CSSharp provide precache resource in core, this plugin is no longer need it.

**Comment by BoTo-sg** [comment]
I fixed it I think, weird bug, the earlier version of MultiAddonManager where it now auto downloads must not of downloaded everything.
I deleted /game/bin/linuxsteamrt64/steamapps and downloaded everything again and now it all shows.

changing zs_classes_mother_default to zs_classes_motherzombie_default in the config will make the mother zombie model not show and when I change it back to zs_classes_mother_default, it works again but that is minimal but just letting you know on that one.

**Comment by BoTo-sg** [comment]
I have traced this bug for good, took a bit to pin point it. 
I loaded your earlier version preview-1.0.2 and it structures zombiesharp.db differently, everything works but if I load your newer version stable-1.1.2, you will run into the problems described here.

each version was tested with zombiesharp.db deleted and only on stable-1.1.2 was the problem there in regards to zombiesharp.db. Now if I load your newer version stable-1.1.2 and keep zombiesharp.db from preview-1.0.2, it will work fine on stable-1.1.2.

**Comment by Oylneechan** [comment]
> I have traced this bug for good, took a bit to pin point it. I loaded your earlier version preview-1.0.2 and it structures zombiesharp.db differently from stable-1.1.2, everything works but if I load your newer version stable-1.1.2 with a fresh zombiesharp.db, you will run into the problems described here.
> 
> each version was tested with zombiesharp.db deleted and only on stable-1.1.2 was the problem there. Now if I load your newer version stable-1.1.2 and keep zombiesharp.db from preview-1.0.2, it will work fine on stable-1.1.2.

So you fixed it?

I missed look the .db for .pdb file. So yeah your previous .db file probably corrupted for some reason. this .db file it supposed to be "Database" for storing a player classes data like a clientpreference is sourcemod. Delete it will basically recreate a new one on server start.

**Comment by BoTo-sg** [comment]
no it wasn't corrupted, the fresh one that stable-1.1.2 version creates is messed up somehow and differs from preview-1.0

**Comment by Oylneechan** [comment]
I check it again later.

**Comment by Oylneechan** [comment]
Turns out removing the quote symbol from convar work out well.
``zs_classes_human_default "human_default"`` => ``zs_classes_human_default human_default``
but you probably want to remove .db file again after you remove the quote symbol

```// Default Class for Human
// -
// Default: "human_default"
zs_classes_human_default human_default

// Default Class for Zombie
// -
// Default: "zombie_default"
zs_classes_zombie_default zombie_default

// Default Class for MotherZombie
// -
// Default: "motherzombie"
zs_classes_motherzombie_default motherzombie
```
