### ISSUE TITLE
Error invoking callback when rejoining which leads to server crash

### ISSUE THREAD

**Issue by BoTo-sg** [Oylneechan/ZombieSharp#7]
Once the game mode starts (doesn't happen during warmup if you have zs_infect_enable_warmup 0) and disconnect and rejoin again, it will produce this which if you keep doing this leads to server crash.

This was tested with just me testing and no other players.
This happens at the beginning of the game during countdown and after becoming zombie.

16:12:11 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '32766' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ZombieSharp.ZombieSharp.HumanizeClient(CCSPlayerController client, Boolean force) in E:\Github\ZSharp\ZombieSharp\ZombieSharp\ZombieSharp.cs:line 255
   at ZombieSharp.ZombieSharp.<>c__DisplayClass31_0.<OnPlayerSpawn>b__0() in E:\Github\ZSharp\ZombieSharp\ZombieSharp\EventModule.cs:line 326
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120

**Comment by Oylneechan** [comment]
I do not recommend having zs_infect_enable_warmup '1' since it has potential memory corrupt. and this going to be difficult to solving since I already tested it many times and still have no issue with it.

**Comment by BoTo-sg** [comment]
Update on this, it was caused by mp_disconnect_kills_players set to 0 but I thought I had it set to 1
Error invoking callback still remains.
